version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: itii-mysql
    restart: unless-stopped

    env_file:
      - ./.env.db.prod

    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./project_ta_prod.sql:/docker-entrypoint-initdb.d/init.sql:ro

    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - itii-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: itii-dev-phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 100M

    depends_on:
      db:
        condition: service_healthy

    networks:
      - itii-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`database.osp101.dev`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls.certresolver=devresolver"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pma-auth.basicauth.users=admin:$apr1$lydYMqG0$AbMOMkXB8gaiEmeg0ie1y"
      - "traefik.http.routers.pma.middlewares=pma-auth"



volumes:
  mysql_data_prod:

networks:
  itii-network:
    external: true
